config/routes.rb
Rails.application.routes.draw do
  root 'ideas#index'
  get 'sessions/new'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :labels
  resources :ideas
  resources :reactions, only: %i(create destroy)
end

app/models/label.rb
class Label < ActiveRecord::Base
  has_and_belongs_to_many :ideas
  validates :title, presence: true
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :logged_in_user
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:title, :published)
    end
end

app/views/labels/_form.html.erb
<%= render 'layouts/header' %>
<%= form_for(@label) do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% @label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= render 'layouts/footer' %>

app/views/labels/edit.html.erb
<%= render 'layouts/header' %>
<h1>Editing Label</h1>

<%= render 'form' %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>
<%= render 'layouts/footer' %>

app/views/labels/index.html.erb
<%= render 'layouts/header' %>
<p id="notice"><%= notice %></p>

<h1>Listing Labels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.title %></td>
        <td><%= label.published %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path %>
<%= render 'layouts/footer' %>

app/views/labels/new.html.erb
<%= render 'layouts/header' %>
<h1>New Label</h1>

<%= render 'form' %>

<%= link_to 'Back', labels_path %>
<%= render 'layouts/footer' %>

app/views/labels/show.html.erb
<%= render 'layouts/header' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @label.title %>
</p>

<% @label.ideas.each do |ideas| %>
  <%= link_to ideas.body, idea_path(ideas) %>
<% end %>
<%= render 'layouts/footer' %>