config/routes.rb
Rails.application.routes.draw do
  root 'ideas#index'
  get 'sessions/new'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :labels
  resources :ideas
  resources :reactions, only: %i(create destroy)
end

app/views/layouts/_footer.html.erb
<footer>

  <p>Create by Balloonbros</p>

  <%= link_to "sample app", root_path, id: "logo" %>
  <nav>
    <ul>
      <li>  <%= link_to 'New Label', new_label_path %></li>
      <li><%= link_to "Home", root_path %></li>
      <% if logged_in? %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Log in", login_path, id: 'login' %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header">

<h1>ロゴ</h1>

  <% if params[:status] == '1' %>
  <p><%= link_to 'Memo', ideas_path(request.query_parameters.merge(status: 0)) %>・Matome</p>
  <% else %>
  <p>Memo・<%= link_to 'Matome', ideas_path(request.query_parameters.merge(status: 1)) %></p>
  <% end %>

<%= link_to 'New Idea', new_idea_path, :class => "add blue" %>

<br>

</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_side.html.erb
<ul class="post-list">
  <% @ideas.each do |idea| %>
    <li class="post">
      <div class="post-title"><%= idea.title %></div>
      <div><%= strip_tags markdown idea.body %></div>
      <% idea.labels.each do |label|  %>
        <%= link_to label.title, label_path(label)  %>
      <% end %>
      <div class="action">
        <%= link_to '', idea, class: "fa fa-search" %>
        <%= link_to '', edit_idea_path(idea), class: "fa fa-pencil" %>
        <%= link_to '', idea, method: :delete, data: { confirm: '投稿を削除しますか?' }, class: "fa fa-trash" %>
      </div>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sutekki</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>